title: Sample input variable schema
schemaVersion: 1.1.0
version: "20200110"
locale: "en"
groupings:
- title: "SSH Key"
  variables:
  - ${provide_ssh_key}
- title: "SSH Configuration"
  variables:
  - ${ssh_provided_key}
  visible: ${provide_ssh_key} 
- title: "Availabilty Domain"
  variables:
  - ${availability_domain}
- title: "VCN Options"
  variables:
  - ${VPC_CIDR}
  - ${vcn_dns_label}
  - ${useExistingVcn}
  - ${hide_public_subnet}
  - ${hide_private_subnet}
- title: "Custom VCN"
  variables:
  - ${myVcn}
  visibility: ${useExistingVcn}
- title: "Airflow Options"
  variables: 
  - ${master_instance_shape}
  - ${airflow_options}
  - ${executor}
- title: "Airflow Extra Packages"
  variables:
  - ${all}
  - ${all_dbs}
  - ${async}
  - ${aws}
  - ${azure}
  - ${celery}
  - ${cloudant}
  - ${crypto}
  - ${devel}
  - ${devel_hadoop}
  - ${druid}
  - ${gcp}
  - ${github_enterprise}
  - ${google_auth}
  - ${hashicorp}
  - ${hdfs}
  - ${hive}
  - ${jdbc}
  - ${kerberos}
  - ${kubernetes}
  - ${ldap}
  - ${mssql}
  - ${mysql}
  - ${oracle}
  - ${password}
  - ${postgres}
  - ${presto}
  - ${qds}
  - ${rabbitmq}
  - ${redis}
  - ${samba}
  - ${slack}
  - ${ssh}
  - ${vertica}
  - ${masterSubnet}
  visible: ${airflow_options}
- title: "Worker Node Options"
  variables:
  - ${worker_instance_shape}
  - ${worker_node_count}
  - ${enable_block_volumes}
  - ${block_volumes_per_worker}
  - ${data_blocksize_in_gbs}
  - ${customize_block_volume_performance}
  - ${block_volume_high_performance}
  - ${block_volume_cost_savings}
  - ${clusterSubnet}
  visible: 
    and:
      - ${airflow_options}
      - not: 
        - eq:
          - ${executor}
          - "local"
- title: "Pre-Defined"
  variables:
  - ${region}
  - ${compartment_ocid}
  - ${tenancy_ocid}
  - ${OELImageOCID}
  - ${oci_service_gateway}
  - ${AD}
  - ${vpus_per_gb}
  visible: false

variables:
  useExistingVcn:
    type: boolean 
    title: "Use Existing VCN"
    description: "Click to use existing VCN, otherwise VCN and Subnets will be created"
    required: true

  myVcn:
    type: oci:core:vcn:id
    title: "Existing VCN"
    description: "Select Existing VCN"
    dependsOn:
      compartmentId: ${compartment_ocid}
    visible: ${useExistingVcn}
    required: true
 
  masterSubnet:
    type: oci:core:subnet:id
    title: "Airflow Master Subnet"
    description: "Select Subnet - Ensure the Subnet is in the same Availability Domain selected above"
    dependsOn:
      compartmentId: ${compartment_ocid}
      vcnId: ${myVcn}
      hidePrivateSubnet: ${hide_private_subnet}
    visible: ${useExistingVcn}
    required: true
    
  clusterSubnet:
    type: oci:core:subnet:id
    title: "Airflow Worker Subnet"
    description: "Select Subnet - Ensure the Subnet is in the same Availability Domain selected above"
    dependsOn:
      compartmentId: ${compartment_ocid}
      vcnId: ${myVcn}
      hidePublicSubnet: ${hide_public_subnet}
    visible: ${useExistingVcn}
    required: true
  
  hide_private_subnet:
    type: boolean
    title: "Deploy Airflow Master to Public Networks"
    description: "If you wish to deploy to private networks and use VPN, un-check this"
    default: true
    visible: ${useExistingVcn}

  hide_public_subnet:
    type: boolean
    title: "Deploy Airflow Workers to Private Network Only"
    description: "This is highly suggested, disable at your own risk"
    default: true
    visible: ${useExistingVcn}

  availability_domain:
    type: oci:identity:availabilitydomain:name 
    title: "Availability Domain"
    description: "Select AD"
    dependsOn:
      compartmentId: ${compartment_ocid}
    required: true

  master_instance_shape:
    type: oci:core:instanceshape:name
    title: "Shape of Airflow Master"
    default: "VM.Standard2.4"
    required: true
    dependsOn:
      compartmentId: ${compartment_ocid}

  worker_instance_shape:
    type: oci:core:instanceshape:name
    title: "Shape of Worker Nodes"
    default: "VM.Standard2.4"
    required: true
    dependsOn:
      compartmentId: ${compartment_ocid}

  worker_node_count:
    type: integer
    title: "Number of Worker Nodes"
    description: "Select number of worker nodes"
    default: 0

  ssh_provided_key:
    type: string
    title: "SSH Public Key"
    description: "Copy/Paste the contents of your SSH Public Key"
    required: true
    default: ""

  data_blocksize_in_gbs:
    type: integer
    title: "Data Block Volume Size ( GB )"
    description: "700 to 32,768 "
    minimum: 700
    maximum: 32768
    required: true
    visible: ${enable_block_volumes}

  block_volumes_per_worker:
    type: integer
    title: "Number of Block Volumes for Data"
    description: "0 to 29"
    minimum: 0 
    maximum: 29
    required: true
    visible: ${enable_block_volumes} 

  customize_block_volume_performance:
    type: boolean
    title: "Custom Block Volume Performance"
    description: "Click to customize Block Volume performance.  Default profile is Balanced. When enabled, only select one sub-option."
    default: false
    visible: ${enable_block_volumes}

  block_volume_high_performance:
    type: boolean
    title: "High Performance Block Volumes"
    description: "Click to enable High Performance for Data Block Volumes.  This comes at a higher cost per GB."
    default: false
    visible: 
      and:
        - ${enable_block_volumes}
        - ${customize_block_volume_performance}

  block_volume_cost_savings:
    type: boolean
    title: "Lower Cost Block Volumes"
    description: "Click to enable Lower Cost for Data Block Volumes.  This lowers performance for cost savings per GB."
    default: false
    visible:
      and:
        - ${enable_block_volumes}
        - ${customize_block_volume_performance}

  VPC_CIDR:
    type: string
    title: "VPC CIDR for VCN"
    description: "Customize VCN top level CIDR"

  vcn_dns_label:
    type: string
    title: "VCN DNS Label"
    description: "Set the VCN DNS label to be used when creating VCN.  Default is 'airflowvcn' which sets the VCN domain to 'airflowvcn.oraclevcn.com'"

  enable_block_volumes:
    type: boolean
    title: "Enable Block Volumes for Data"
    description: "Check to enable Block Volumes for use with Data. This is optional for BM.Dense hosts, required for all others."
    default: true 

  provide_ssh_key:
    type: boolean
    title: "Provide SSH Key"
    description: "Un-Check to generate SSH key as part of deployment process.  This is NOT recommended for persistent environments, you should provide your own key for any production deployment."

  executor:
    type: enum
    enum:
    - "local"
    - "celery"
    title: "Airflow Executor"
    default: "local"
    description: "Select Airflow Executor"
    required: true
    visible: ${airflow_options}

  airflow_options:
    type: boolean
    title: "Airflow Advanced Customization"
    description: "Click to enable advanced customization of Airflow installation options, including which hooks are installed, and what executor to use."
    default: false
    required: true

  all:
    type: boolean
    title: "all"
    default: "false"

  all_dbs:
    type: boolean
    title: "all_dbs"
    default: "false"

  async:
    type: boolean
    title: "async"
    default: "false"

  aws:
    type: boolean
    title: "aws"
    default: "false"

  azure:
    type: boolean
    title: "azure"
    default: "false"

  celery:
    type: boolean
    title: "celery"
    default: "false"

  cloudant:
    type: boolean
    title: "cloudant"
    default: "false"

  crypto:
    type: boolean
    title: "crypto"
    default: "false"

  devel:
    type: boolean
    title: "devel"
    default: "false"

  devel_hadoop:
    type: boolean
    title: "devel_hadoop"
    default: "false"

  druid:
    type: boolean
    title: "druid"
    default: "false"

  gcp:
    type: boolean
    title: "gcp"
    default: "false"

  github_enterprise:
    type: boolean
    title: "github_enterprise"
    default: "false"

  google_auth:
    type: boolean
    title: "google_auth"
    default: "false"

  hashicorp:
    type: boolean
    title: "hashicorp"
    default: "false"

  hdfs:
    type: boolean
    title: "hdfs"
    default: "false"

  hive:
    type: boolean
    title: "hive"
    default: "false"

  jdbc:
    type: boolean
    title: "jdbc"
    default: "false"

  kerberos:
    type: boolean
    title: "kerberos"
    default: "false"

  kubernetes:
    type: boolean
    title: "kubernetes"
    default: "false"

  ldap:
    type: boolean
    title: "ldap"
    default: "false"

  mssql:
    type: boolean
    title: "mssql"
    default: "false"

  mysql:
    type: boolean
    title: "mysql"
    default: "true"

  oracle:
    type: boolean
    title: "oracle"
    default: "true"

  password:
    type: boolean
    title: "password"
    default: "false"

  postgres:
    type: boolean
    title: "postgres"
    default: "false"

  presto:
    type: boolean
    title: "presto"
    default: "false"

  qds:
    type: boolean
    title: "qds"
    default: "false"

  rabbitmq:
    type: boolean
    title: "rabbitmq"
    default: "false"

  redis:
    type: boolean
    title: "redis"
    default: "false"

  samba:
    type: boolean
    title: "samba"
    default: "false"

  slack:
    type: boolean
    title: "slack"
    default: "false"

  ssh:
    type: boolean
    title: "ssh"
    default: "true"

  vertica:
    type: boolean
    title: "vertica"
    default: "false"

 
